# Generated by Django 6.0.2 on 2026-02-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs_app', '0002_brand_engine_remove_specialty_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
        ),
        migrations.CreateModel(
            name='PythonLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва бібліотеки')),
                ('purpose', models.CharField(max_length=255, verbose_name='Призначення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок теми')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='labs_app.category', verbose_name='Категорія')),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
