# Generated by Django 6.0.2 on 2026-03-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs_app', '0003_category_pythonlibrary_remove_car_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pythonlibrary',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.AddField(
            model_name='pythonlibrary',
            name='usage',
            field=models.CharField(default='Default usage', max_length=255, verbose_name='Для чого потрібна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='', verbose_name='Опис теми'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs_app.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва теми'),
        ),
    ]
