# Generated by Django 6.0.2 on 2026-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs_app', '0004_remove_category_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PythonLibrary',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Теми'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default='', verbose_name='Повний зміст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='topic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AddField(
            model_name='topic',
            name='short_description',
            field=models.TextField(default='', verbose_name='Короткий опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
