# Generated by Django 6.0.2 on 2026-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs_app', '0005_delete_pythonlibrary_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва бібліотеки')),
                ('description', models.TextField(verbose_name='Опис')),
                ('link', models.URLField(blank=True, verbose_name='Посилання на документацію')),
            ],
            options={
                'verbose_name': 'Бібліотека',
                'verbose_name_plural': 'Бібліотеки',
            },
        ),
    ]
