# Generated by Django 6.0.2 on 2026-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs_app', '0006_pythonlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='Повний матеріал теми'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics/', verbose_name='Логотип/Фото'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Вартість курсу'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='short_description',
            field=models.TextField(verbose_name='Короткий анонс'),
        ),
    ]
